services:
  rag:
    build: .
    depends_on:
      - qdrant
      - redis
    stdin_open: true
    tty: true
    environment:
      QDRANT_URL: http://qdrant:6333
      REDIS_URL: redis://redis
    env_file:
      - .env
  redis:
    image: redis:7.4.2-alpine
  qdrant:
    image: qdrant/qdrant:latest
